# -*- coding: utf-8 -*-
"""WeatherApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jmcOuIbLiX1DSk-4alyl6z5y8a28F9s
"""

import requests

# API URL for hourly weather forecast in London
API_URL = "https://samples.openweathermap.org/data/2.5/forecast/hourly?q=London,us&appid=b6907d289e10d714a6e88b30761fae22"

# Function to fetch weather data from the API
def get_weather_data():
    response = requests.get(API_URL)
    if response.status_code == 200:
        return response.json()
    else:
        print("Error fetching weather data.")
        return None

# Function to get temperature by date
def get_temperature_by_date(weather_data, date):
    for forecast in weather_data['list']:
        if forecast['dt_txt'] == date:
            return forecast['main']['temp']
    return None

# Function to get wind speed by date
def get_wind_speed_by_date(weather_data, date):
    for forecast in weather_data['list']:
        if forecast['dt_txt'] == date:
            return forecast['wind']['speed']
    return None

# Function to get pressure by date
def get_pressure_by_date(weather_data, date):
    for forecast in weather_data['list']:
        if forecast['dt_txt'] == date:
            return forecast['main']['pressure']
    return None

# Main function
def main():
    # Fetch weather data
    weather_data = get_weather_data()
    if weather_data is None:
        return

    # User interaction loop
    while True:
        print("\nSelect an option:")
        print("1. Get temperature")
        print("2. Get wind speed")
        print("3. Get pressure")
        print("0. Exit")

        option = input("Enter your choice: ")

        if option == '1':
            date = input("Enter date (YYYY-MM-DD HH:mm:ss): ")
            temperature = get_temperature_by_date(weather_data, date)
            if temperature is not None:
                print(f"Temperature: {temperature}°C")
            else:
                print("Weather data not found for the specified date.")

        elif option == '2':
            date = input("Enter date (YYYY-MM-DD HH:mm:ss): ")
            wind_speed = get_wind_speed_by_date(weather_data, date)
            if wind_speed is not None:
                print(f"Wind Speed: {wind_speed} m/s")
            else:
                print("Weather data not found for the specified date.")

        elif option == '3':
            date = input("Enter date (YYYY-MM-DD HH:mm:ss): ")
            pressure = get_pressure_by_date(weather_data, date)
            if pressure is not None:
                print(f"Pressure: {pressure} hPa")
            else:
                print("Weather data not found for the specified date.")

        elif option == '0':
            print("Exiting program...")
            break

        else:
            print("Invalid option. Please select again.")

if __name__ == "__main__":
    main()